const fs=require('fs');
const css=`<style>
body{font-family:'Times New Roman',serif;font-size:13pt;padding:2cm 3cm;color:#000}
.cap{text-align:center;font-style:italic;font-size:13pt;margin:20px 0 4px}
table{width:15.5cm;border-collapse:collapse;margin:0 auto 8px;table-layout:fixed}
th,td{border:1px solid #000;padding:3px 5px;vertical-align:middle;font-size:10.5pt;word-wrap:break-word;overflow-wrap:break-word}
th{background:#eee;font-weight:700;text-align:center}
td:nth-child(3){text-align:center}
h2{font-size:14pt;margin:0 0 12px}
</style>`;
const cg=`<colgroup><col style="width:3cm"><col style="width:2.8cm"><col style="width:2.2cm"><col style="width:3.5cm"><col style="width:4cm"></colgroup>`;
const T=[
{n:'2.14',nm:'CHUC_VU',r:[['id','INT','NOT NULL','PK','Mã chức vụ'],['ten','Nvarchar(100)','NOT NULL','','Tên chức vụ'],['mo_ta','Nvarchar(MAX)','NULL','','Mô tả'],['la_he_thong','Bit','NOT NULL','','Chức vụ hệ thống'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.15',nm:'QUYEN_HAN',r:[['id','INT','NOT NULL','PK','Mã quyền hạn'],['ma_code','Nvarchar(100)','NOT NULL','','Mã code quyền'],['ten','Nvarchar(200)','NOT NULL','','Tên quyền'],['module','Nvarchar(100)','NOT NULL','','Module'],['thu_tu','INT','NULL','','Thứ tự']]},
{n:'2.16',nm:'CHUC_VU_QUYEN',r:[['ma_chuc_vu','INT','NOT NULL','PK, FK→CHUC_VU','Mã chức vụ'],['ma_quyen','INT','NOT NULL','PK, FK→QUYEN_HAN','Mã quyền']]},
{n:'2.17',nm:'NGUOI_DUNG',r:[['id','INT','NOT NULL','PK','Mã người dùng'],['ma_chuc_vu','INT','NULL','FK→CHUC_VU','Chức vụ'],['email','Nvarchar(100)','NOT NULL','','Email đăng nhập'],['mat_khau','Nvarchar(255)','NOT NULL','','Mật khẩu mã hóa'],['ho_ten','Nvarchar(100)','NOT NULL','','Họ và tên'],['loai_tai_khoan','Nvarchar(10)','NOT NULL','','Loại tài khoản'],['trang_thai','Bit','NOT NULL','','Hoạt động/Khóa'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.18',nm:'PHIEN_DANG_NHAP',r:[['id','INT','NOT NULL','PK','Mã phiên'],['ma_nguoi_dung','INT','NOT NULL','FK→NGUOI_DUNG','Người dùng'],['token_phien','Nvarchar(MAX)','NOT NULL','','JWT token'],['dang_hoat_dong','Bit','NOT NULL','','Hiệu lực'],['thoi_gian_dang_nhap','Datetime2','NOT NULL','','Thời điểm đăng nhập'],['dia_chi_ip','Nvarchar(45)','NULL','','Địa chỉ IP']]},
{n:'2.19',nm:'THONG_BAO',r:[['id','INT','NOT NULL','PK','Mã thông báo'],['ma_nguoi_dung','INT','NOT NULL','FK→NGUOI_DUNG','Người nhận'],['tieu_de','Nvarchar(255)','NOT NULL','','Tiêu đề'],['noi_dung','Nvarchar(MAX)','NULL','','Nội dung'],['da_doc','Bit','NOT NULL','','Đã đọc'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.20',nm:'KHACH_HANG',r:[['id','INT','NOT NULL','PK','Mã KH'],['ma_khach_hang','Nvarchar(20)','NOT NULL','','Mã KH'],['ho_ten','Nvarchar(100)','NOT NULL','','Tên KH'],['dien_thoai','Nvarchar(15)','NULL','','Điện thoại'],['email','Nvarchar(100)','NULL','','Email'],['dia_chi','Nvarchar(MAX)','NULL','','Địa chỉ'],['ma_so_thue','Nvarchar(20)','NULL','','MST'],['trang_thai_kh','Nvarchar(20)','NULL','','Trạng thái'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.21',nm:'DU_AN',r:[['id','INT','NOT NULL','PK','Mã dự án'],['ma_khach_hang','INT','NOT NULL','FK→KHACH_HANG','Khách hàng'],['ma_du_an','Nvarchar(20)','NOT NULL','','Mã dự án'],['ten_du_an','Nvarchar(200)','NOT NULL','','Tên dự án'],['trang_thai','Nvarchar(20)','NOT NULL','','Trạng thái'],['ngay_bat_dau','Date','NULL','','Ngày bắt đầu'],['han_hoan_thanh','Date','NULL','','Hạn hoàn thành'],['dia_chi_thi_cong','Nvarchar(MAX)','NULL','','Địa chỉ thi công'],['ghi_chu','Nvarchar(MAX)','NULL','','Ghi chú'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.22',nm:'MAU_SAN_PHAM',r:[['id','INT','NOT NULL','PK','Mã mẫu SP'],['ma_code','Nvarchar(50)','NOT NULL','','Mã code'],['ten_san_pham','Nvarchar(200)','NOT NULL','','Tên mẫu'],['loai_san_pham','Nvarchar(20)','NOT NULL','','Loại SP'],['danh_muc','Nvarchar(100)','NULL','','Danh mục'],['chieu_rong_mac_dinh','INT','NULL','','Rộng (mm)'],['chieu_cao_mac_dinh','INT','NULL','','Cao (mm)'],['cau_truc_json','Nvarchar(MAX)','NULL','','Cấu trúc JSON'],['anh_dai_dien','Nvarchar(MAX)','NULL','','Ảnh đại diện']]},
{n:'2.23',nm:'SAN_PHAM_DU_AN',r:[['id','INT','NOT NULL','PK','Mã SP dự án'],['ma_du_an','INT','NOT NULL','FK→DU_AN','Dự án'],['ma_mau_san_pham','INT','NOT NULL','FK→MAU_SAN_PHAM','Mẫu SP'],['ten_rieng','Nvarchar(200)','NULL','','Tên riêng'],['so_luong','INT','NOT NULL','','Số lượng'],['chieu_rong_tuy_chinh','INT','NULL','','Rộng (mm)'],['chieu_cao_tuy_chinh','INT','NULL','','Cao (mm)'],['cau_hinh_snapshot','Nvarchar(MAX)','NULL','','Cấu hình BOM'],['vi_tri_lap_dat','Nvarchar(200)','NULL','','Vị trí lắp đặt'],['trang_thai','Nvarchar(50)','NULL','','Trạng thái'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.24',nm:'VAT_TU_BOM',r:[['id','INT','NOT NULL','PK','Mã vật tư'],['ma_san_pham_du_an','INT','NOT NULL','FK→SAN_PHAM_DU_AN','SP dự án'],['ma_ton_kho','INT','NULL','FK→TON_KHO','Liên kết kho'],['loai_vat_tu','Nvarchar(50)','NOT NULL','','Loại vật tư'],['ma_code','Nvarchar(100)','NULL','','Mã code'],['ten_vat_tu','Nvarchar(255)','NOT NULL','','Tên vật tư'],['chieu_dai_mm','INT','NULL','','Dài cắt (mm)'],['so_luong','Decimal(10,3)','NOT NULL','','Số lượng'],['hao_hut_mm','INT','NULL','','Hao hụt (mm)'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.25',nm:'BAO_GIA',r:[['id','INT','NOT NULL','PK','Mã báo giá'],['ma_du_an','INT','NULL','FK→DU_AN','Dự án'],['ma_bao_gia','Nvarchar(30)','NOT NULL','','Số báo giá'],['ngay_bao_gia','Date','NOT NULL','','Ngày lập'],['phien_ban','INT','NOT NULL','','Phiên bản'],['trang_thai','Nvarchar(20)','NOT NULL','','Trạng thái'],['phan_tram_loi_nhuan','Decimal(5,2)','NULL','','% lợi nhuận'],['phan_tram_vat','Decimal(5,2)','NULL','','% VAT'],['phi_van_chuyen','Decimal(15,2)','NULL','','Phí VC'],['tong_tien_cuoi','Decimal(15,2)','NULL','','Tổng tiền'],['so_tien_dat_coc','Decimal(15,2)','NULL','','Đặt cọc'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.26',nm:'CHI_TIET_BAO_GIA',r:[['id','INT','NOT NULL','PK','Mã chi tiết'],['ma_bao_gia','INT','NOT NULL','FK→BAO_GIA','Báo giá cha'],['ma_mau_san_pham','INT','NULL','FK→MAU_SAN_PHAM','Mẫu SP'],['ten_san_pham','Nvarchar(200)','NOT NULL','','Tên SP'],['chieu_rong','Decimal(10,2)','NULL','','Rộng (mm)'],['chieu_cao','Decimal(10,2)','NULL','','Cao (mm)'],['so_luong','INT','NOT NULL','','Số lượng'],['don_gia','Decimal(15,2)','NULL','','Đơn giá'],['thanh_tien','Decimal(15,2)','NULL','','Thành tiền']]},
{n:'2.27',nm:'GIAO_DICH_TAI_CHINH',r:[['id','INT','NOT NULL','PK','Mã giao dịch'],['ma_du_an','INT','NULL','FK→DU_AN','Dự án'],['ma_bao_gia','INT','NULL','FK→BAO_GIA','Báo giá nguồn'],['ma_giao_dich','Nvarchar(50)','NOT NULL','','Mã GD'],['ngay_giao_dich','Date','NOT NULL','','Ngày GD'],['loai_giao_dich','Nvarchar(10)','NOT NULL','','Thu / Chi'],['danh_muc','Nvarchar(100)','NULL','','Danh mục'],['so_tien','Decimal(15,2)','NOT NULL','','Số tiền'],['dien_giai','Nvarchar(MAX)','NULL','','Diễn giải'],['trang_thai','Nvarchar(15)','NOT NULL','','Trạng thái'],['phuong_thuc_thanh_toan','Nvarchar(50)','NULL','','Phương thức TT'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.28',nm:'CHI_TIET_GIAO_DICH',r:[['id','INT','NOT NULL','PK','Mã chi tiết'],['ma_giao_dich','INT','NOT NULL','FK→GIAO_DICH_TAI_CHINH','Giao dịch cha'],['ten_muc','Nvarchar(200)','NOT NULL','','Tên mục'],['so_luong','INT','NULL','','Số lượng'],['don_gia','Decimal(15,2)','NULL','','Đơn giá'],['thanh_tien','Decimal(15,2)','NOT NULL','','Thành tiền']]},
{n:'2.29',nm:'CONG_NO',r:[['id','INT','NOT NULL','PK','Mã công nợ'],['ma_du_an','INT','NULL','FK→DU_AN','Dự án'],['loai_cong_no','Nvarchar(15)','NOT NULL','','Phải thu/trả'],['nha_cung_cap','Nvarchar(200)','NULL','','NCC'],['tong_no','Decimal(15,2)','NOT NULL','','Tổng nợ'],['da_thanh_toan','Decimal(15,2)','NOT NULL','','Đã TT'],['trang_thai','Nvarchar(10)','NOT NULL','','Trạng thái'],['ngay_tao','Datetime2','NOT NULL','','Thời gian tạo']]},
{n:'2.30',nm:'TON_KHO',r:[['id','INT','NOT NULL','PK','Mã vật tư'],['ma_vat_tu','Nvarchar(50)','NOT NULL','','Mã VT'],['ten_vat_tu','Nvarchar(255)','NOT NULL','','Tên VT'],['loai_vat_tu','Nvarchar(50)','NOT NULL','','Loại VT'],['don_vi','Nvarchar(50)','NULL','','Đơn vị'],['don_gia','Decimal(15,2)','NULL','','Đơn giá'],['nha_cung_cap','Nvarchar(200)','NULL','','NCC'],['muc_canh_bao_ton','INT','NULL','','Mức tồn min']]},
{n:'2.31',nm:'GIAO_DICH_KHO',r:[['id','INT','NOT NULL','PK','Mã GD kho'],['ma_ton_kho','INT','NOT NULL','FK→TON_KHO','Vật tư kho'],['ma_du_an','INT','NULL','FK→DU_AN','Dự án'],['loai_giao_dich','Nvarchar(10)','NOT NULL','','Nhập/Xuất'],['so_luong','Decimal(10,2)','NOT NULL','','Số lượng'],['ghi_chu','Nvarchar(MAX)','NULL','','Ghi chú'],['ngay_giao_dich','Datetime2','NOT NULL','','Thời gian GD']]}
];
let h=`<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Thiết kế bảng</title>${css}</head><body>`;
h+=`<h2>2.6.2. Thiết kế bảng</h2>`;
for(const t of T){
h+=`<p class="cap">Bảng ${t.n}. Chi tiết bảng ${t.nm}</p><table>${cg}`;
h+=`<tr><th>Tên trường</th><th>Kiểu dữ liệu</th><th>Ràng buộc</th><th>Khóa</th><th>Mô tả</th></tr>`;
for(const r of t.r)h+=`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`;
h+=`</table>`;}
h+=`</body></html>`;
fs.writeFileSync('Thiet_Ke_Bang.html',h,'utf8');
console.log('OK');
